# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:           SOC 401 Final Project
tagline:          ''
description:      'Rent Stabilization Policies and Housing Affordability in Seattle' 
url:              "https://ymzakaria.github.io"
baseurl:          "/soc401-ymzakaria"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/ymzakaria/soc401-ymzakaria/
